import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:syncfusion_flutter_pdf/pdf.dart' as syncfusion;

class PdfService {
  /// Generates a PDF file containing recognized Braille text and saves it to local device storage.
  /// Returns the generated PDF file path.
  Future<File> generatePdfFromText({
    required String title,
    required String textContent,
  }) async {
    final pdf = pw.Document();

    final sanitizedTitle = title.replaceAll(RegExp(r'[^\w\s\-]'), '_').trim();
    final documentTitle = sanitizedTitle.isNotEmpty ? sanitizedTitle : 'Recognized_Braille_Document';

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Text(
                documentTitle,
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blue900,
                ),
              ),
            ),
            pw.SizedBox(height: 12),
            pw.Paragraph(
              text: textContent,
              style: const pw.TextStyle(
                fontSize: 14,
                lineSpacing: 4.0,
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Divider(),
            pw.Text(
              'Generated by VisionMate Optical Braille Recognition',
              style: const pw.TextStyle(
                fontSize: 10,
                color: PdfColors.grey700,
              ),
            ),
          ];
        },
      ),
    );

    final outputDir = await getApplicationDocumentsDirectory();
    final file = File('${outputDir.path}/$documentTitle.pdf');
    await file.writeAsBytes(await pdf.save());
    debugPrint('PdfService: Successfully generated PDF at ${file.path}');
    return file;
  }

  /// Extracts text content from a local PDF file.
  Future<String> extractTextFromPdf(File pdfFile) async {
    try {
      final bytes = await pdfFile.readAsBytes();
      final syncfusion.PdfDocument document = syncfusion.PdfDocument(inputBytes: bytes);
      
      final syncfusion.PdfTextExtractor extractor = syncfusion.PdfTextExtractor(document);
      final String extractedText = extractor.extractText();
      
      document.dispose();
      debugPrint('PdfService: Extracted ${extractedText.length} characters from ${pdfFile.path}');
      return extractedText.trim();
    } catch (e) {
      debugPrint('PdfService: Error extracting text from PDF file ${pdfFile.path}: $e');
      return '';
    }
  }
}
