org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot
android.overrideVersionCheck=true
kotlin.jvm.target.validation.mode=ignore
skip-build-dependency-validation=true
android-skip-build-dependency-validation=true
ignore-deprecation-warns=true
android.suppressUnsupportedCompileSdk=36


